/**
 * Kanban
 * An API to perform Kanban operations
 *
 * OpenAPI spec version: v1
 * Contact: mspe@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DataChartDetailFront } from "./dataChartDetailFront";

export interface DashboardProdFront { 
    affect?: Array<DataChartDetailFront>;
    line?: Array<DataChartDetailFront>;
    sect?: Array<DataChartDetailFront>;
    proj?: Array<DataChartDetailFront>;
    total?: Array<DataChartDetailFront>;
      
}