/**
 * Kanban
 * An API to perform Kanban operations
 *
 * OpenAPI spec version: v1
 * Contact: mspe@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserLoginFront { 
    username: string;
    password: string;
}